stages:
  - styles
  - build

cache:
  paths:
    - node_modules

styles:
  stage: styles
  image: node:14
  tags:
    - docker
    - web_client
  variables:
    NODE_ENV: test
  script:
    - node_modules/.bin/check-dependencies || npm install
    - node_modules/.bin/eslint ./src

build:
  stage: build
  image: node:14
  tags:
    - docker
    - web_client
  artifacts:
    paths:
      - build
    expire_in: 1 day
  when: manual
  script:
    - npm run build